### ISSUE TITLE
[BUG] broken link in docs

### ISSUE THREAD

**Issue by ikamensh** [pytorch/rl#2174] opened 2024-05-28 16:21 UTC
## Describe the bug

Docs https://pytorch.org/rl/stable/tutorials/coding_ppo.html have broken link for "coding_ppo". When clicking on open in colab, this opens: 
"""
Notebook not found
There was an error loading this notebook. Ensure that the file is accessible and try again.
https://github.com/pytorch/rl/blob/gh-pages/_downloads/c4cc1ccac40ca535b79628b7eb0bbe18/coding_ppo.py
Fetch for https://api.github.com/repos/pytorch/rl/contents/_downloads/c4cc1ccac40ca535b79628b7eb0bbe18?per_page=100&ref=gh-pages failed: {
"""

This link worked though: https://colab.research.google.com/github/pytorch/rl/blob/gh-pages/0.4/_downloads/e2a5193e019585d9cfa26d3eebfd8be3/coding_ppo.ipynb

**Comment by vmoens** [comment] 2024-05-29 10:38
Yep unfortunately the automated link to the colabs are broken. Maybe @svekars can help?

**Comment by matteobettini** [comment] 2024-05-31 07:54
Duplicate of #2134

**Comment by vmoens** [comment] 2024-07-04 09:28
Closed by #2268

**Closed by vmoens** 2024-07-04 09:28 UTC
Labels: bug
