### ISSUE TITLE
[Feature Request] Multi-Agent tutorial

### ISSUE THREAD

**Issue by mattiasmar** [pytorch/rl#923] opened 2023-02-16 19:33 UTC
## Motivation
I want to utilize TorchRL for multi-agent simulations. I would like to connect the TorchRL to an existing simulator and I want to learn how different agents can be simultaneously controlled by different policies. An example not relying on  mujjocco or openai, but rather a small toy simulator (e.g. dots moving along a matrix or something other simple) would be useful to allow readers to focus on the inner  workings of TorchRL.
An advanced version of the tutorial would be one that simultaneously controls different kind of agents (each with a different action spaces) and through that, the tutorial would showcase to the benefits of the TensorDict.

## Solution
A new tutorial in the git.

**Comment by matteobettini** [comment] 2023-03-01 17:28
duplicate of #862 

I am working on it, there are several things to sort out but I aim to do a tutorial using vmas https://github.com/proroklab/VectorizedMultiAgentSimulator

**Comment by matteobettini** [comment] 2023-04-17 10:05
#1027 Shows some examples of multiagent training in [VMAS](https://github.com/proroklab/VectorizedMultiAgentSimulator)

**Closed** 2023-04-17 11:31 UTC
Labels: enhancement
