### ISSUE TITLE
[BUG] PPO Tutorial returns `_torchrl.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl` in colab

### ISSUE THREAD

**Issue by umutsoysal** [pytorch/rl#975] opened 2023-03-17 02:54 UTC
Following the tutorial in the google colab I am hitting to an error that says:

ImportError: /usr/local/lib/python3.9/dist-packages/torchrl/_torchrl.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/10604284/225800584-0f4345c4-da7b-4101-9c9f-bd34e6e8d6de.png">

**Comment by vmoens** [comment] 2023-03-17 07:55
Hey thanks for reporting this
After a quick check and some heavy sweating I can confirm that it is not caused by torchrl but by colab not yet being upgraded to torch 2.0
To run the tutorial, you'll need to decorate it with `!pip install torch -U` for a little longer :) 
I'll close the issue once we have upgrade the torch version in colab.

**Comment by DuaneNielsen** [comment] 2023-03-27 04:21
Hey Vincent, might be worth adding a note to the tutorial that the tutorial requires a fresh install of PyTorch 2 or something like that.  I hit this error also when reusing an existing PyTorch 1.x environment.  The PyTorch binaries are pretty big so I'd be surprised if it's not common practice among at least some users to try to re-use old environments to save space.

**Comment by anonymouscnuser** [comment] 2023-03-27 21:51
@vmoens Is there a version compatible with torch 1.x?

**Comment by vmoens** [comment] 2023-03-28 07:59
One solution is to build the library from github directly. The import box would look like this:
```python
!pip3 install git+https://github.com/pytorch/rl@v0.1.0
!pip3 install gym[mujoco]
!pip3 install tqdm
```
Optionally you can use the nightly (simply remove the `@v0.1.0` from above).
Hope that helps!

**Comment by ChengDaHaI** [comment] 2023-07-07 19:18
HI @vmoens, I face this issue too.

My system is torchrl 0.1.0 (pip install git+https://github.com/pytorch/rl@v0.1.0) + pytorch 1.12.1 +cuda11.3.

I have creat python venv several time by conda and still get the same error:
`./envs/torch_rl/lib/python3.9/site-packages/torchrl/_torchrl.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl`

Any idea how to solve it?

Thanks
Hai

**Comment by vmoens** [comment] 2023-07-07 20:08
This error is usually due to installing torchrl wheels with a version of pytorch that does not match.
Can you provide the whole sequence?

Also: have you tried torch > 1.13, with torchrl 0.1.1 and 0.1.2 for tensordict?

**Comment by ChengDaHaI** [comment] 2023-07-07 20:13
What do you mean by the whole sequence?

My system is:

- torchrl 0.1.0 (pip install git+https://github.com/pytorch/rl@v0.1.0)

- pytorch 1.12.1 (pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113) 
- cuda 11.3


I did not try torch> 1.13 since my nvidia driver+cuda version does not support that.

**Comment by vmoens** [comment] 2023-07-12 12:44
Yep so the bug is that you're installing a package (torchrl 0.1) that requires torch 2.0, but you're using torch 1.12

If you want to use torch 1.12, you should do `pip install git+https://github.com/pytorch/rl@v0.1.1`

In the future release, we'll only guarantee compatibility with torch 1.13 onward. Is there any reason you are using torch 1.12 and not 2.0?

**Comment by ChengDaHaI** [comment] 2023-07-13 17:02
> If you want to use torch 1.12, you should do `pip install git+https://github.com/pytorch/rl@v0.1.1`

This is how I install torchrl with torch1.12, but it still raises error.

> In the future release, we'll only guarantee compatibility with torch 1.13 onward. Is there any reason you are using torch 1.12 and not 2.0?

No really, I reinstall torch 2.0 and it works with torch v0.1.1

**Closed** 2023-07-17 02:22 UTC
Labels: bug
