### ISSUE TITLE
Not knowing Which key is causing shape mismatch

### ISSUE THREAD

**Issue by aminrezaee** [pytorch/rl#2222] opened 2024-06-11 08:32 UTC
Hi there. I'm having problems with my environment rollout. Sometimes my environment shapes are changing somehow. If in the except block I'm going to mention, you don't set any type for the exception it would be much better. Because alongside the exception about shape mismatch another exception would raise saying which key caused this problem.
here is the line I'm suggesting to change:
https://github.com/pytorch/rl/blob/3787a9edeea03cb9e98b928824072b939c327776/torchrl/data/tensor_specs.py#L3978C20-L3978C28
and here is the line a raising shape mismatch:
https://github.com/pytorch/rl/blob/3787a9edeea03cb9e98b928824072b939c327776/torchrl/data/tensor_specs.py#L587

note that if the shapes of observations are different currently just the shape mismatch exception would be raised due to different exception types.

**Comment by vmoens** [comment] 2024-06-11 08:42
> Sometimes my environment shapes are changing somehow

Is this expected? We have allowed dynamic shapes in nightlies, it will be part of the next major release. You can just set `-1` to the shapes that should change.

RE your suggestion:
what about capturing this `RuntimeError` separately, and tell user which key is the culprit of the shape mismatch?

**Comment by aminrezaee** [comment] 2024-06-11 09:07
> Is this expected?

No. The changes of shapes aren't desired and in my codes are actually a bug. 


> what about capturing this `RuntimeError` separately

I agree. That would be nicer.

**Comment by vmoens** [comment] 2024-06-11 09:26
Ok I guess my initial understanding was that you were expecting your shapes to change and wanted to work around the exceptions, I now understand that the problem is that the exception are not informative enough
I can patch that quickly! 
If you can think of anything else that would help you debug this sort of situation I'd be happy to help

**Closed** 2024-06-11 09:42 UTC
